# docker-compose.yml
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB} # myshop
      POSTGRES_USER: ${POSTGRES_USER} # postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${POSTGRES_HOST} # db
      POSTGRES_DB: ${POSTGRES_DB} # myshop
      POSTGRES_USER: ${POSTGRES_USER} # postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # 1234
      POSTGRES_PORT: 5432
      PORT: ${PORT:-3001}
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    healthcheck:
      test: curl --fail http://localhost:${PORT:-3001} || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data: